CREATE TABLE IF NOT EXISTS app_metadata (
  metadata_key TEXT PRIMARY KEY,
  metadata_value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS departments (
  department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_name VARCHAR(150) NOT NULL UNIQUE,
  location VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS positions (
  position_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_title VARCHAR(150) NOT NULL UNIQUE,
  base_salary NUMERIC(12, 2) NOT NULL CHECK (base_salary >= 0)
);

CREATE TABLE IF NOT EXISTS leave_types (
  leave_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leave_name VARCHAR(150) NOT NULL UNIQUE,
  description TEXT
);

CREATE TABLE IF NOT EXISTS projects (
  project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name VARCHAR(150) NOT NULL UNIQUE,
  start_date DATE,
  end_date DATE,
  CHECK (start_date IS NULL OR end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS employees (
  employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE,
  contact_number VARCHAR(30),
  birthdate DATE,
  hire_date DATE,
  department_id INTEGER NOT NULL,
  position_id INTEGER NOT NULL,
  manager_id INTEGER,
  employment_status VARCHAR(30) NOT NULL DEFAULT 'Active' CHECK (
    employment_status IN ('Active', 'Probationary', 'On Leave', 'Resigned')
  ),
  CHECK (manager_id IS NULL OR manager_id <> employee_id),
  CONSTRAINT employees_department_id_fkey
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT employees_position_id_fkey
    FOREIGN KEY (position_id) REFERENCES positions(position_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT employees_manager_id_fkey
    FOREIGN KEY (manager_id) REFERENCES employees(employee_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS attendance (
  attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL,
  attendance_date DATE NOT NULL,
  time_in TIME NOT NULL,
  time_out TIME,
  CHECK (time_out IS NULL OR time_in < time_out),
  CONSTRAINT attendance_employee_id_fkey
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS leave_requests (
  leave_request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL,
  leave_type_id INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
  request_date DATE NOT NULL,
  CHECK (end_date >= start_date),
  CONSTRAINT leave_requests_employee_id_fkey
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT leave_requests_leave_type_id_fkey
    FOREIGN KEY (leave_type_id) REFERENCES leave_types(leave_type_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS employee_projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL,
  project_id INTEGER NOT NULL,
  UNIQUE (employee_id, project_id),
  CONSTRAINT employee_projects_employee_id_fkey
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT employee_projects_project_id_fkey
    FOREIGN KEY (project_id) REFERENCES projects(project_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);
